import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {Activity,ArrowUpRight,ChevronRight,Focus,Globe,Info,Layers3,Pause,RotateCcw,RotateCw,Search,Sprout,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {SUPPORTED_LANGUAGES} from './i18n';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0,mode:'explore',growth:0};
const GROWTH_MARKS=[{years:0,label:'Birth'},{years:5,label:'5'},{years:10,label:'10'},{years:15,label:'15'},{years:20,label:'20'},{years:25,label:'25 yr'}];
export default function Home(){
 const {t,i18n}=useTranslation(['ui','anatomy']);
 const systemLabel=(id:SystemId)=>t(`anatomy:systems.${id}.name`);
 const systemDescription=(id:SystemId)=>t(`anatomy:systems.${id}.description`);
 const translatedExplanation=(name:string,systemId:SystemId)=>{const key=`anatomy:explanations.${name.toLowerCase()}`;return i18n.exists(key)?t(key):systemDescription(systemId);};
 useEffect(()=>{document.documentElement.dir=SUPPORTED_LANGUAGES.find(l=>l.code===i18n.language)?.dir??'ltr';document.documentElement.lang=i18n.language;},[i18n.language]);
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,mode:s.mode,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const setMode=(mode:'explore'|'growth')=>{setChosen(null);setDetails(false);setPanel(null);setState(s=>mode==='growth'?{...s,mode,visible:['skeletal'],selected:[],isolate:false,explode:0,rotate:false,view:'three-quarter',reset:s.reset+1}:{...s,mode,visible:DEFAULT_VISIBLE,selected:[],isolate:false,growth:0,reset:s.reset+1});};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> {t('ui:eyebrow')}</div><h1>Human Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} {t('ui:modeledPieces')} <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Explorer panels">{state.mode==='explore'&&<Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label={t('ui:findStructure')}><Search size={18}/><span>{t('ui:findStructure')}</span><kbd>/</kbd></Button>}<Button variant="ghost" className={state.mode==='growth'?'active':''} aria-pressed={state.mode==='growth'} onClick={()=>setMode(state.mode==='growth'?'explore':'growth')} aria-label={t('ui:skeletonGrowth')}><Sprout size={18}/><span>{state.mode==='growth'?t('ui:exitGrowth'):t('ui:skeletonGrowth')}</span></Button><span className="language-switch"><Globe size={15}/><NativeSelect aria-label={t('ui:language')} value={i18n.language} onChange={e=>i18n.changeLanguage(e.target.value)}>{SUPPORTED_LANGUAGES.map(l=><NativeSelectOption key={l.code} value={l.code}>{l.name}</NativeSelectOption>)}</NativeSelect></span><Button variant="ghost" className="icon-button" aria-label={t('ui:about')} onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  {state.mode==='explore'&&<section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>{t('ui:systems')}</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label={t('ui:systems')}><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>{t('ui:all')}</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>{t('ui:skeleton')}</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>{t('ui:organs')}</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={systemLabel(s.id)} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{systemLabel(s.id)}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={systemLabel(s.id)} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} {t('ui:piecesVisible')}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>{t('ui:hideAll')}</Button></div>
  </section>}
  {state.mode==='explore'&&panel==='search'&&<section className="search-panel glass" aria-label={t('ui:findStructure')}><div className="panel-heading"><span>{t('ui:findStructure')}</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label={t('ui:findStructure')}><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder={t('ui:searchPlaceholder')} aria-label={t('ui:findStructure')} showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>{t('ui:noMatches')}</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {t(c.elements.length===1?'ui:piece':'ui:pieces')}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?t('ui:searchNoteActive'):t('ui:searchNoteIdle')}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.mode==='growth'?(state.growth*25<1?t('ui:newborn'):t('ui:growingAge',{age:(state.growth*25).toFixed(state.growth*25<5?1:0)})):state.isolate?(chosen?.name??t('ui:selectedStructure')):state.explode>.95?t('ui:anatomicalInventory'):state.explode>.05?t('ui:separatedStructures'):t('ui:adultHumanMale')}</span><span className="caption-line"/></div>
  {state.mode==='growth'?
  <div className="bottom-dock glass"><div className="explode-control"><div className="explode-label"><label id="growth-label">{t('ui:growthLabel')}</label><output>{state.growth*25<1?t('ui:birth'):`${(state.growth*25).toFixed(state.growth*25<5?1:0)} yr`}</output></div><Slider aria-labelledby="growth-label" min={0} max={100} step={1} value={[state.growth*100]} onValueChange={v=>setState(s=>({...s,growth:(Array.isArray(v)?v[0]:v)/100}))}/><div className="slider-endpoints">{GROWTH_MARKS.map(m=><span key={m.years}>{m.years===0?t('ui:birth'):m.label}</span>)}</div><p className="search-note">{t('ui:growthModeSources')}</p></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label={t('ui:returnToBirth')}><RotateCcw size={18}/><span>{t('ui:reset')}</span></Button></div>
  :<div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label={t('ui:systems')}><Layers3 size={20}/><span>{t('ui:systems')}</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">{t('ui:explodeAnatomy')}</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>{t('ui:assembled')}</span><span>{t('ui:everyPiece')}</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label={t('ui:reset')}><RotateCcw size={18}/><span>{t('ui:reset')}</span></Button></div>}
  <footer className="studio-footer"><span>{state.explode>.8?t('ui:dragToPan'):t('ui:dragToOrbit')} <b>·</b> {t('ui:pinchToZoom')} <b>·</b> {t('ui:tapToInspect')}</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>{t('ui:sourceAndCredits')} <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>{t('ui:preparingAnatomy')}</strong><span>{progress}% · {t('ui:loadingPieces')} {atlas?.parts.length.toLocaleString()??'2,234'} {t('ui:pieces')}</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>{t('ui:reloadViewer')}</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?systemLabel(system.id):t('ui:anatomyFallback')}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?translatedExplanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">{t('ui:systemOverviewNote')}</span>}<div className="structure-meta"><span>{t('ui:atlasReference')}<strong>{chosen?.id}</strong></span><span>{t('ui:selectedPieces')}<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>{t('ui:includedStructures')}</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>{t('ui:andMorePieces',{count:selectedParts.length-50})}</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">{t('ui:viewSource')} <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?t('ui:showSurrounding'):t('ui:isolateStructure')}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>{t('ui:clearSelection')}</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">{t('ui:sourceScope')}</div><SheetTitle className="structure-title">{t('ui:aBodyRevealed')}</SheetTitle><SheetDescription>{t('ui:aboutIntro')}</SheetDescription><div className="about-copy"><p><strong>{t('ui:aboutMaleHeading')}</strong><br/>{t('ui:aboutMaleBody')}</p><p>{t('ui:aboutPara2')}</p><p>{t('ui:aboutPara3')}</p><h3>{t('ui:sourceHeading')}</h3><p>{t('ui:sourceAttribution')}</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">{t('ui:datasetLicense')} <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">{t('ui:originalGeometry')} <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">{t('ui:readPublication')} <ArrowUpRight size={14}/></a><h3>{t('ui:growthModeHeading')}</h3><p>{t('ui:growthModeSources')}</p></div></SheetContent></Sheet>
 </main>;
}
